// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjPSd8CvB04O7HRYVWcFCUmo4LmJ9cP2o',
    appId: '1:806306911425:web:3baee601bce076253c7040',
    messagingSenderId: '806306911425',
    projectId: 'new-halo-task',
    authDomain: 'new-halo-task.firebaseapp.com',
    storageBucket: 'new-halo-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5-rl-OID1CJbJYfghHw9KX3TsPgvFCw',
    appId: '1:806306911425:android:28a56a4c38d841993c7040',
    messagingSenderId: '806306911425',
    projectId: 'new-halo-task',
    storageBucket: 'new-halo-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2sNqmEK3w2ZdMCHTvCy9a8oRdjLHovWI',
    appId: '1:806306911425:ios:5f59309c0af5fd203c7040',
    messagingSenderId: '806306911425',
    projectId: 'new-halo-task',
    storageBucket: 'new-halo-task.appspot.com',
    iosClientId: '806306911425-crjhrnovcnn2li0tp54tj8h2oqa2pdd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.newHaloTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2sNqmEK3w2ZdMCHTvCy9a8oRdjLHovWI',
    appId: '1:806306911425:ios:a3f86151b28ded023c7040',
    messagingSenderId: '806306911425',
    projectId: 'new-halo-task',
    storageBucket: 'new-halo-task.appspot.com',
    iosClientId: '806306911425-3j0uvgee069chem4s2h1q5pkue2ss7n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newHaloTask.RunnerTests',
  );
}
