// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlxcsB3heoZw9_IpIs7m_xHDe4y_Ay8-Q',
    appId: '1:139398389507:web:58ecd6392e02c836511336',
    messagingSenderId: '139398389507',
    projectId: 'halo-74f17',
    authDomain: 'halo-74f17.firebaseapp.com',
    storageBucket: 'halo-74f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRn9HFYjRpug9W6T3j76Cc_DqOcT-yu4',
    appId: '1:139398389507:android:314a38fc73bab256511336',
    messagingSenderId: '139398389507',
    projectId: 'halo-74f17',
    storageBucket: 'halo-74f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD539VsESs1i8lozRNIshdP1ziOTeAU4vU',
    appId: '1:139398389507:ios:d08a44562992a1c5511336',
    messagingSenderId: '139398389507',
    projectId: 'halo-74f17',
    storageBucket: 'halo-74f17.appspot.com',
    iosBundleId: 'com.example.newHaloTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD539VsESs1i8lozRNIshdP1ziOTeAU4vU',
    appId: '1:139398389507:ios:ce298ea6b89cab28511336',
    messagingSenderId: '139398389507',
    projectId: 'halo-74f17',
    storageBucket: 'halo-74f17.appspot.com',
    iosBundleId: 'com.example.newHaloTask.RunnerTests',
  );
}
